version: '3.4'

services:
  registrationapi:
    image: ${DOCKER_REGISTRY-}registrationapi
    build:
      context: .
      dockerfile: Services/Registration/Registration.API/Dockerfile

  emailapi:
    image: ${DOCKER_REGISTRY-}emailapi
    build:
      context: .
      dockerfile: Services/Email/EmailService.API/Dockerfile

  smsserviceapi:
    image: ${DOCKER_REGISTRY-}smsapi
    build:
      context: .
      dockerfile: Services/SMS/SMSService.API/Dockerfile
  
 
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2017-latest


  rabbitmq:
    image: rabbitmq:3-management-alpine


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2


  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
  

  

  healthcheck:
    image: ${DOCKER_REGISTRY-}healthcheck
    build:
      context: .
      dockerfile: HealthCheck/HealthCheck/Dockerfile

volumes:
  elasticsearch-data:


